/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityEntry { 'action' : string, 'timestamp' : Timestamp }
export interface AdminStats {
  'todayBookings' : bigint,
  'platformRevenue' : bigint,
  'totalUsers' : bigint,
  'totalOwners' : bigint,
}
export interface Booking {
  'id' : string,
  'status' : BookingStatus,
  'ownerId' : string,
  'userId' : string,
  'createdAt' : Timestamp,
  'upiRef' : string,
  'category' : Category,
  'amountInr' : bigint,
  'itemRef' : string,
}
export type BookingStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'accepted' : null } |
  { 'declined' : null };
export type Category = { 'retail' : null } |
  { 'food' : null } |
  { 'play' : null } |
  { 'stay' : null };
export interface CategoryEntry {
  'id' : string,
  'name' : string,
  'isActive' : boolean,
  'iconEmoji' : string,
  'searchKeywords' : Array<string>,
  'tableType' : Category,
}
export interface FoodItem {
  'id' : string,
  'ownerId' : string,
  'isAvailable' : boolean,
  'description' : string,
  'itemName' : string,
  'isVeg' : boolean,
  'priceInr' : bigint,
}
export interface Notification {
  'id' : string,
  'title' : string,
  'body' : string,
  'createdAt' : Timestamp,
  'soundType' : SoundType,
  'isRead' : boolean,
  'target' : string,
}
export interface OwnerRecord {
  'id' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'businessName' : string,
  'isActive' : boolean,
  'activityLog' : Array<ActivityEntry>,
  'isVerified' : boolean,
  'upiId' : string,
  'isBanned' : boolean,
  'category' : Category,
  'passwordHash' : string,
  'phone' : string,
  'locationText' : string,
  'gpsLat' : number,
  'gpsLng' : number,
}
export interface OwnerRevenue {
  'ownerId' : string,
  'businessName' : string,
  'todayRevenue' : bigint,
  'totalRevenue' : bigint,
}
export interface PlaySlot {
  'id' : string,
  'ownerId' : string,
  'surfaceType' : string,
  'bookedByUserId' : [] | [string],
  'hourlyRate' : bigint,
  'description' : string,
  'slotTime' : string,
  'isBooked' : boolean,
}
export type Result = { 'ok' : null } |
  { 'err' : string };
export type Result_1 = { 'ok' : UserRecord } |
  { 'err' : string };
export type Result_10 = { 'ok' : CategoryEntry } |
  { 'err' : string };
export type Result_2 = { 'ok' : Ticket } |
  { 'err' : string };
export type Result_3 = { 'ok' : Notification } |
  { 'err' : string };
export type Result_4 = { 'ok' : Booking } |
  { 'err' : string };
export type Result_5 = { 'ok' : OwnerRecord } |
  { 'err' : string };
export type Result_6 = { 'ok' : StayRoom } |
  { 'err' : string };
export type Result_7 = { 'ok' : RetailItem } |
  { 'err' : string };
export type Result_8 = { 'ok' : PlaySlot } |
  { 'err' : string };
export type Result_9 = { 'ok' : FoodItem } |
  { 'err' : string };
export interface RetailItem {
  'id' : string,
  'inStock' : boolean,
  'ownerId' : string,
  'itemName' : string,
  'quantity' : bigint,
  'category' : string,
  'priceInr' : bigint,
}
export type SoundType = { 'alarm' : null } |
  { 'ping' : null } |
  { 'silent' : null };
export interface StayRoom {
  'id' : string,
  'ownerId' : string,
  'pricePerNight' : bigint,
  'isAvailable' : boolean,
  'amenities' : Array<string>,
  'roomName' : string,
  'bookedDates' : Array<string>,
}
export interface Ticket {
  'id' : string,
  'status' : TicketStatus,
  'messages' : Array<TicketMessage>,
  'ownerId' : [] | [string],
  'createdAt' : Timestamp,
  'description' : string,
  'imageUrl' : [] | [string],
  'category' : string,
  'raisedBy' : string,
}
export interface TicketMessage {
  'text' : string,
  'sender' : string,
  'timestamp' : Timestamp,
}
export type TicketStatus = { 'resolved' : null } |
  { 'open' : null };
export type Timestamp = bigint;
export type UserId = string;
export interface UserRecord {
  'id' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'activityLog' : Array<ActivityEntry>,
  'isBanned' : boolean,
  'passwordHash' : string,
  'phone' : string,
  'locationText' : string,
  'gpsLat' : number,
  'gpsLng' : number,
}
export type UserRole = { 'admin' : null } |
  { 'owner' : null } |
  { 'user' : null };
export interface _SERVICE {
  'addBookedDate' : ActorMethod<[string, string], Result>,
  'addCategory' : ActorMethod<
    [string, string, Category, Array<string>],
    Result_10
  >,
  'addFoodItem' : ActorMethod<
    [string, string, bigint, boolean, string],
    Result_9
  >,
  'addPlaySlot' : ActorMethod<
    [string, string, string, bigint, string],
    Result_8
  >,
  'addRetailItem' : ActorMethod<
    [string, string, bigint, string, bigint],
    Result_7
  >,
  'addStayRoom' : ActorMethod<
    [string, string, Array<string>, bigint],
    Result_6
  >,
  'addTicketMessage' : ActorMethod<[string, string, string], Result>,
  'banUser' : ActorMethod<[string, boolean], Result>,
  'completeOwnerOnboarding' : ActorMethod<
    [string, string, Category, string],
    Result_5
  >,
  'createBooking' : ActorMethod<
    [string, string, Category, string, bigint, string],
    Result_4
  >,
  'createNotification' : ActorMethod<
    [string, string, string, SoundType],
    Result_3
  >,
  'createTicket' : ActorMethod<
    [string, [] | [string], string, string, [] | [string]],
    Result_2
  >,
  'deleteCategory' : ActorMethod<[string], Result>,
  'deleteFoodItem' : ActorMethod<[string], Result>,
  'getActiveCategories' : ActorMethod<[], Array<CategoryEntry>>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllCategories' : ActorMethod<[], Array<CategoryEntry>>,
  'getAllFoodItems' : ActorMethod<[], Array<FoodItem>>,
  'getAllNotifications' : ActorMethod<[], Array<Notification>>,
  'getAllOwners' : ActorMethod<[], Array<OwnerRecord>>,
  'getAllPlaySlots' : ActorMethod<[], Array<PlaySlot>>,
  'getAllRetailItems' : ActorMethod<[], Array<RetailItem>>,
  'getAllStayRooms' : ActorMethod<[], Array<StayRoom>>,
  'getAllTickets' : ActorMethod<[], Array<Ticket>>,
  'getAllUsers' : ActorMethod<[], Array<UserRecord>>,
  'getBookingsByOwner' : ActorMethod<[string], Array<Booking>>,
  'getBookingsByUser' : ActorMethod<[string], Array<Booking>>,
  'getFoodItemsByOwner' : ActorMethod<[string], Array<FoodItem>>,
  'getNotificationsByTarget' : ActorMethod<[string], Array<Notification>>,
  'getOwnerById' : ActorMethod<[string], [] | [OwnerRecord]>,
  'getOwnersByCategory' : ActorMethod<[Category], Array<OwnerRecord>>,
  'getPlaySlotsByOwner' : ActorMethod<[string], Array<PlaySlot>>,
  'getRetailItemsByOwner' : ActorMethod<[string], Array<RetailItem>>,
  'getRevenueByOwner' : ActorMethod<[], Array<OwnerRevenue>>,
  'getStayRoomsByOwner' : ActorMethod<[string], Array<StayRoom>>,
  'getTicketsByOwner' : ActorMethod<[string], Array<Ticket>>,
  'getTicketsByUser' : ActorMethod<[string], Array<Ticket>>,
  'getUserById' : ActorMethod<[string], [] | [UserRecord]>,
  'logActivity' : ActorMethod<[string, string], undefined>,
  'markNotificationRead' : ActorMethod<[string], Result>,
  'resolveTicket' : ActorMethod<[string], Result>,
  'signinUser' : ActorMethod<[string, string], Result_1>,
  'signupUser' : ActorMethod<
    [string, string, string, UserRole, number, number, string],
    Result_1
  >,
  'toggleSlotBooking' : ActorMethod<[string, boolean, [] | [string]], Result>,
  'updateBookingStatus' : ActorMethod<[string, BookingStatus], Result>,
  'updateCategory' : ActorMethod<
    [string, string, string, boolean, Array<string>],
    Result
  >,
  'updateFoodItem' : ActorMethod<
    [string, string, bigint, boolean, string, boolean],
    Result
  >,
  'updateOwnerProfile' : ActorMethod<[string, string, string, boolean], Result>,
  'updatePlaySlot' : ActorMethod<
    [string, string, string, bigint, string],
    Result
  >,
  'updateRetailItem' : ActorMethod<
    [string, string, bigint, string, boolean, bigint],
    Result
  >,
  'updateStayRoom' : ActorMethod<
    [string, string, Array<string>, bigint, boolean],
    Result
  >,
  'updateUserProfile' : ActorMethod<
    [string, string, string, number, number],
    Result
  >,
  'verifyOwner' : ActorMethod<[string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];