/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const Category = IDL.Variant({
  'retail' : IDL.Null,
  'food' : IDL.Null,
  'play' : IDL.Null,
  'stay' : IDL.Null,
});
export const CategoryEntry = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'iconEmoji' : IDL.Text,
  'searchKeywords' : IDL.Vec(IDL.Text),
  'tableType' : Category,
});
export const Result_10 = IDL.Variant({
  'ok' : CategoryEntry,
  'err' : IDL.Text,
});
export const FoodItem = IDL.Record({
  'id' : IDL.Text,
  'ownerId' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'itemName' : IDL.Text,
  'isVeg' : IDL.Bool,
  'priceInr' : IDL.Nat,
});
export const Result_9 = IDL.Variant({ 'ok' : FoodItem, 'err' : IDL.Text });
export const PlaySlot = IDL.Record({
  'id' : IDL.Text,
  'ownerId' : IDL.Text,
  'surfaceType' : IDL.Text,
  'bookedByUserId' : IDL.Opt(IDL.Text),
  'hourlyRate' : IDL.Nat,
  'description' : IDL.Text,
  'slotTime' : IDL.Text,
  'isBooked' : IDL.Bool,
});
export const Result_8 = IDL.Variant({ 'ok' : PlaySlot, 'err' : IDL.Text });
export const RetailItem = IDL.Record({
  'id' : IDL.Text,
  'inStock' : IDL.Bool,
  'ownerId' : IDL.Text,
  'itemName' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
  'priceInr' : IDL.Nat,
});
export const Result_7 = IDL.Variant({ 'ok' : RetailItem, 'err' : IDL.Text });
export const StayRoom = IDL.Record({
  'id' : IDL.Text,
  'ownerId' : IDL.Text,
  'pricePerNight' : IDL.Nat,
  'isAvailable' : IDL.Bool,
  'amenities' : IDL.Vec(IDL.Text),
  'roomName' : IDL.Text,
  'bookedDates' : IDL.Vec(IDL.Text),
});
export const Result_6 = IDL.Variant({ 'ok' : StayRoom, 'err' : IDL.Text });
export const UserId = IDL.Text;
export const Timestamp = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'owner' : IDL.Null,
  'user' : IDL.Null,
});
export const ActivityEntry = IDL.Record({
  'action' : IDL.Text,
  'timestamp' : Timestamp,
});
export const OwnerRecord = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'businessName' : IDL.Text,
  'isActive' : IDL.Bool,
  'activityLog' : IDL.Vec(ActivityEntry),
  'isVerified' : IDL.Bool,
  'upiId' : IDL.Text,
  'isBanned' : IDL.Bool,
  'category' : Category,
  'passwordHash' : IDL.Text,
  'phone' : IDL.Text,
  'locationText' : IDL.Text,
  'gpsLat' : IDL.Float64,
  'gpsLng' : IDL.Float64,
});
export const Result_5 = IDL.Variant({ 'ok' : OwnerRecord, 'err' : IDL.Text });
export const BookingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'accepted' : IDL.Null,
  'declined' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'status' : BookingStatus,
  'ownerId' : IDL.Text,
  'userId' : IDL.Text,
  'createdAt' : Timestamp,
  'upiRef' : IDL.Text,
  'category' : Category,
  'amountInr' : IDL.Nat,
  'itemRef' : IDL.Text,
});
export const Result_4 = IDL.Variant({ 'ok' : Booking, 'err' : IDL.Text });
export const SoundType = IDL.Variant({
  'alarm' : IDL.Null,
  'ping' : IDL.Null,
  'silent' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : Timestamp,
  'soundType' : SoundType,
  'isRead' : IDL.Bool,
  'target' : IDL.Text,
});
export const Result_3 = IDL.Variant({ 'ok' : Notification, 'err' : IDL.Text });
export const TicketStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'open' : IDL.Null,
});
export const TicketMessage = IDL.Record({
  'text' : IDL.Text,
  'sender' : IDL.Text,
  'timestamp' : Timestamp,
});
export const Ticket = IDL.Record({
  'id' : IDL.Text,
  'status' : TicketStatus,
  'messages' : IDL.Vec(TicketMessage),
  'ownerId' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'raisedBy' : IDL.Text,
});
export const Result_2 = IDL.Variant({ 'ok' : Ticket, 'err' : IDL.Text });
export const AdminStats = IDL.Record({
  'todayBookings' : IDL.Nat,
  'platformRevenue' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalOwners' : IDL.Nat,
});
export const UserRecord = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'activityLog' : IDL.Vec(ActivityEntry),
  'isBanned' : IDL.Bool,
  'passwordHash' : IDL.Text,
  'phone' : IDL.Text,
  'locationText' : IDL.Text,
  'gpsLat' : IDL.Float64,
  'gpsLng' : IDL.Float64,
});
export const OwnerRevenue = IDL.Record({
  'ownerId' : IDL.Text,
  'businessName' : IDL.Text,
  'todayRevenue' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
});
export const Result_1 = IDL.Variant({ 'ok' : UserRecord, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'addBookedDate' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'addCategory' : IDL.Func(
      [IDL.Text, IDL.Text, Category, IDL.Vec(IDL.Text)],
      [Result_10],
      [],
    ),
  'addFoodItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Bool, IDL.Text],
      [Result_9],
      [],
    ),
  'addPlaySlot' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [Result_8],
      [],
    ),
  'addRetailItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
      [Result_7],
      [],
    ),
  'addStayRoom' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
      [Result_6],
      [],
    ),
  'addTicketMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
  'banUser' : IDL.Func([IDL.Text, IDL.Bool], [Result], []),
  'completeOwnerOnboarding' : IDL.Func(
      [IDL.Text, IDL.Text, Category, IDL.Text],
      [Result_5],
      [],
    ),
  'createBooking' : IDL.Func(
      [IDL.Text, IDL.Text, Category, IDL.Text, IDL.Nat, IDL.Text],
      [Result_4],
      [],
    ),
  'createNotification' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, SoundType],
      [Result_3],
      [],
    ),
  'createTicket' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [Result_2],
      [],
    ),
  'deleteCategory' : IDL.Func([IDL.Text], [Result], []),
  'deleteFoodItem' : IDL.Func([IDL.Text], [Result], []),
  'getActiveCategories' : IDL.Func([], [IDL.Vec(CategoryEntry)], ['query']),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllCategories' : IDL.Func([], [IDL.Vec(CategoryEntry)], ['query']),
  'getAllFoodItems' : IDL.Func([], [IDL.Vec(FoodItem)], ['query']),
  'getAllNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getAllOwners' : IDL.Func([], [IDL.Vec(OwnerRecord)], ['query']),
  'getAllPlaySlots' : IDL.Func([], [IDL.Vec(PlaySlot)], ['query']),
  'getAllRetailItems' : IDL.Func([], [IDL.Vec(RetailItem)], ['query']),
  'getAllStayRooms' : IDL.Func([], [IDL.Vec(StayRoom)], ['query']),
  'getAllTickets' : IDL.Func([], [IDL.Vec(Ticket)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserRecord)], ['query']),
  'getBookingsByOwner' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'getBookingsByUser' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'getFoodItemsByOwner' : IDL.Func([IDL.Text], [IDL.Vec(FoodItem)], ['query']),
  'getNotificationsByTarget' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getOwnerById' : IDL.Func([IDL.Text], [IDL.Opt(OwnerRecord)], ['query']),
  'getOwnersByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(OwnerRecord)],
      ['query'],
    ),
  'getPlaySlotsByOwner' : IDL.Func([IDL.Text], [IDL.Vec(PlaySlot)], ['query']),
  'getRetailItemsByOwner' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(RetailItem)],
      ['query'],
    ),
  'getRevenueByOwner' : IDL.Func([], [IDL.Vec(OwnerRevenue)], ['query']),
  'getStayRoomsByOwner' : IDL.Func([IDL.Text], [IDL.Vec(StayRoom)], ['query']),
  'getTicketsByOwner' : IDL.Func([IDL.Text], [IDL.Vec(Ticket)], ['query']),
  'getTicketsByUser' : IDL.Func([IDL.Text], [IDL.Vec(Ticket)], ['query']),
  'getUserById' : IDL.Func([IDL.Text], [IDL.Opt(UserRecord)], ['query']),
  'logActivity' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'markNotificationRead' : IDL.Func([IDL.Text], [Result], []),
  'resolveTicket' : IDL.Func([IDL.Text], [Result], []),
  'signinUser' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
  'signupUser' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        UserRole,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
      ],
      [Result_1],
      [],
    ),
  'toggleSlotBooking' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
      [Result],
      [],
    ),
  'updateBookingStatus' : IDL.Func([IDL.Text, BookingStatus], [Result], []),
  'updateCategory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Vec(IDL.Text)],
      [Result],
      [],
    ),
  'updateFoodItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Bool, IDL.Text, IDL.Bool],
      [Result],
      [],
    ),
  'updateOwnerProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [Result],
      [],
    ),
  'updatePlaySlot' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [Result],
      [],
    ),
  'updateRetailItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool, IDL.Nat],
      [Result],
      [],
    ),
  'updateStayRoom' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, IDL.Bool],
      [Result],
      [],
    ),
  'updateUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [Result],
      [],
    ),
  'verifyOwner' : IDL.Func([IDL.Text], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Category = IDL.Variant({
    'retail' : IDL.Null,
    'food' : IDL.Null,
    'play' : IDL.Null,
    'stay' : IDL.Null,
  });
  const CategoryEntry = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'iconEmoji' : IDL.Text,
    'searchKeywords' : IDL.Vec(IDL.Text),
    'tableType' : Category,
  });
  const Result_10 = IDL.Variant({ 'ok' : CategoryEntry, 'err' : IDL.Text });
  const FoodItem = IDL.Record({
    'id' : IDL.Text,
    'ownerId' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'itemName' : IDL.Text,
    'isVeg' : IDL.Bool,
    'priceInr' : IDL.Nat,
  });
  const Result_9 = IDL.Variant({ 'ok' : FoodItem, 'err' : IDL.Text });
  const PlaySlot = IDL.Record({
    'id' : IDL.Text,
    'ownerId' : IDL.Text,
    'surfaceType' : IDL.Text,
    'bookedByUserId' : IDL.Opt(IDL.Text),
    'hourlyRate' : IDL.Nat,
    'description' : IDL.Text,
    'slotTime' : IDL.Text,
    'isBooked' : IDL.Bool,
  });
  const Result_8 = IDL.Variant({ 'ok' : PlaySlot, 'err' : IDL.Text });
  const RetailItem = IDL.Record({
    'id' : IDL.Text,
    'inStock' : IDL.Bool,
    'ownerId' : IDL.Text,
    'itemName' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
    'priceInr' : IDL.Nat,
  });
  const Result_7 = IDL.Variant({ 'ok' : RetailItem, 'err' : IDL.Text });
  const StayRoom = IDL.Record({
    'id' : IDL.Text,
    'ownerId' : IDL.Text,
    'pricePerNight' : IDL.Nat,
    'isAvailable' : IDL.Bool,
    'amenities' : IDL.Vec(IDL.Text),
    'roomName' : IDL.Text,
    'bookedDates' : IDL.Vec(IDL.Text),
  });
  const Result_6 = IDL.Variant({ 'ok' : StayRoom, 'err' : IDL.Text });
  const UserId = IDL.Text;
  const Timestamp = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'owner' : IDL.Null,
    'user' : IDL.Null,
  });
  const ActivityEntry = IDL.Record({
    'action' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const OwnerRecord = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'businessName' : IDL.Text,
    'isActive' : IDL.Bool,
    'activityLog' : IDL.Vec(ActivityEntry),
    'isVerified' : IDL.Bool,
    'upiId' : IDL.Text,
    'isBanned' : IDL.Bool,
    'category' : Category,
    'passwordHash' : IDL.Text,
    'phone' : IDL.Text,
    'locationText' : IDL.Text,
    'gpsLat' : IDL.Float64,
    'gpsLng' : IDL.Float64,
  });
  const Result_5 = IDL.Variant({ 'ok' : OwnerRecord, 'err' : IDL.Text });
  const BookingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'accepted' : IDL.Null,
    'declined' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'status' : BookingStatus,
    'ownerId' : IDL.Text,
    'userId' : IDL.Text,
    'createdAt' : Timestamp,
    'upiRef' : IDL.Text,
    'category' : Category,
    'amountInr' : IDL.Nat,
    'itemRef' : IDL.Text,
  });
  const Result_4 = IDL.Variant({ 'ok' : Booking, 'err' : IDL.Text });
  const SoundType = IDL.Variant({
    'alarm' : IDL.Null,
    'ping' : IDL.Null,
    'silent' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : Timestamp,
    'soundType' : SoundType,
    'isRead' : IDL.Bool,
    'target' : IDL.Text,
  });
  const Result_3 = IDL.Variant({ 'ok' : Notification, 'err' : IDL.Text });
  const TicketStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'open' : IDL.Null,
  });
  const TicketMessage = IDL.Record({
    'text' : IDL.Text,
    'sender' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const Ticket = IDL.Record({
    'id' : IDL.Text,
    'status' : TicketStatus,
    'messages' : IDL.Vec(TicketMessage),
    'ownerId' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'raisedBy' : IDL.Text,
  });
  const Result_2 = IDL.Variant({ 'ok' : Ticket, 'err' : IDL.Text });
  const AdminStats = IDL.Record({
    'todayBookings' : IDL.Nat,
    'platformRevenue' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalOwners' : IDL.Nat,
  });
  const UserRecord = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'activityLog' : IDL.Vec(ActivityEntry),
    'isBanned' : IDL.Bool,
    'passwordHash' : IDL.Text,
    'phone' : IDL.Text,
    'locationText' : IDL.Text,
    'gpsLat' : IDL.Float64,
    'gpsLng' : IDL.Float64,
  });
  const OwnerRevenue = IDL.Record({
    'ownerId' : IDL.Text,
    'businessName' : IDL.Text,
    'todayRevenue' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
  });
  const Result_1 = IDL.Variant({ 'ok' : UserRecord, 'err' : IDL.Text });
  
  return IDL.Service({
    'addBookedDate' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'addCategory' : IDL.Func(
        [IDL.Text, IDL.Text, Category, IDL.Vec(IDL.Text)],
        [Result_10],
        [],
      ),
    'addFoodItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Bool, IDL.Text],
        [Result_9],
        [],
      ),
    'addPlaySlot' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [Result_8],
        [],
      ),
    'addRetailItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
        [Result_7],
        [],
      ),
    'addStayRoom' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
        [Result_6],
        [],
      ),
    'addTicketMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result], []),
    'banUser' : IDL.Func([IDL.Text, IDL.Bool], [Result], []),
    'completeOwnerOnboarding' : IDL.Func(
        [IDL.Text, IDL.Text, Category, IDL.Text],
        [Result_5],
        [],
      ),
    'createBooking' : IDL.Func(
        [IDL.Text, IDL.Text, Category, IDL.Text, IDL.Nat, IDL.Text],
        [Result_4],
        [],
      ),
    'createNotification' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, SoundType],
        [Result_3],
        [],
      ),
    'createTicket' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [Result_2],
        [],
      ),
    'deleteCategory' : IDL.Func([IDL.Text], [Result], []),
    'deleteFoodItem' : IDL.Func([IDL.Text], [Result], []),
    'getActiveCategories' : IDL.Func([], [IDL.Vec(CategoryEntry)], ['query']),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllCategories' : IDL.Func([], [IDL.Vec(CategoryEntry)], ['query']),
    'getAllFoodItems' : IDL.Func([], [IDL.Vec(FoodItem)], ['query']),
    'getAllNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getAllOwners' : IDL.Func([], [IDL.Vec(OwnerRecord)], ['query']),
    'getAllPlaySlots' : IDL.Func([], [IDL.Vec(PlaySlot)], ['query']),
    'getAllRetailItems' : IDL.Func([], [IDL.Vec(RetailItem)], ['query']),
    'getAllStayRooms' : IDL.Func([], [IDL.Vec(StayRoom)], ['query']),
    'getAllTickets' : IDL.Func([], [IDL.Vec(Ticket)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserRecord)], ['query']),
    'getBookingsByOwner' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'getBookingsByUser' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'getFoodItemsByOwner' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FoodItem)],
        ['query'],
      ),
    'getNotificationsByTarget' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getOwnerById' : IDL.Func([IDL.Text], [IDL.Opt(OwnerRecord)], ['query']),
    'getOwnersByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(OwnerRecord)],
        ['query'],
      ),
    'getPlaySlotsByOwner' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PlaySlot)],
        ['query'],
      ),
    'getRetailItemsByOwner' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(RetailItem)],
        ['query'],
      ),
    'getRevenueByOwner' : IDL.Func([], [IDL.Vec(OwnerRevenue)], ['query']),
    'getStayRoomsByOwner' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StayRoom)],
        ['query'],
      ),
    'getTicketsByOwner' : IDL.Func([IDL.Text], [IDL.Vec(Ticket)], ['query']),
    'getTicketsByUser' : IDL.Func([IDL.Text], [IDL.Vec(Ticket)], ['query']),
    'getUserById' : IDL.Func([IDL.Text], [IDL.Opt(UserRecord)], ['query']),
    'logActivity' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'markNotificationRead' : IDL.Func([IDL.Text], [Result], []),
    'resolveTicket' : IDL.Func([IDL.Text], [Result], []),
    'signinUser' : IDL.Func([IDL.Text, IDL.Text], [Result_1], []),
    'signupUser' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          UserRole,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
        ],
        [Result_1],
        [],
      ),
    'toggleSlotBooking' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
        [Result],
        [],
      ),
    'updateBookingStatus' : IDL.Func([IDL.Text, BookingStatus], [Result], []),
    'updateCategory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Vec(IDL.Text)],
        [Result],
        [],
      ),
    'updateFoodItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Bool, IDL.Text, IDL.Bool],
        [Result],
        [],
      ),
    'updateOwnerProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [Result],
        [],
      ),
    'updatePlaySlot' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [Result],
        [],
      ),
    'updateRetailItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool, IDL.Nat],
        [Result],
        [],
      ),
    'updateStayRoom' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, IDL.Bool],
        [Result],
        [],
      ),
    'updateUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [Result],
        [],
      ),
    'verifyOwner' : IDL.Func([IDL.Text], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };