/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface OwnerRecord {
    id: UserId;
    subscriptionExpiryDate: Timestamp;
    lastSubscriptionTxId: string;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    businessName: string;
    isActive: boolean;
    lastSubscriptionPaymentDate: Timestamp;
    activityLog: Array<ActivityEntry>;
    subscriptionStatus: SubscriptionStatus;
    isVerified: boolean;
    upiId: string;
    isBanned: boolean;
    category: Category;
    passwordHash: string;
    phone: string;
    locationText: string;
    gpsLat: number;
    gpsLng: number;
}
export interface CategoryEntry {
    id: string;
    name: string;
    isActive: boolean;
    iconEmoji: string;
    searchKeywords: Array<string>;
    tableType: Category;
}
export type Timestamp = bigint;
export type Result_2 = {
    __kind__: "ok";
    ok: Ticket;
} | {
    __kind__: "err";
    err: string;
};
export interface PlaySlot {
    id: string;
    startTime: string;
    endTime: string;
    ownerId: string;
    surfaceType: string;
    bookedByUserId?: string;
    hourlyRate: bigint;
    description: string;
    slotDate: string;
    slotTime: string;
    isBooked: boolean;
}
export type Result_5 = {
    __kind__: "ok";
    ok: OwnerRecord;
} | {
    __kind__: "err";
    err: string;
};
export type Result_1 = {
    __kind__: "ok";
    ok: UserRecord;
} | {
    __kind__: "err";
    err: string;
};
export interface UserRecord {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    activityLog: Array<ActivityEntry>;
    isBanned: boolean;
    passwordHash: string;
    phone: string;
    locationText: string;
    gpsLat: number;
    gpsLng: number;
}
export type Result_4 = {
    __kind__: "ok";
    ok: Booking;
} | {
    __kind__: "err";
    err: string;
};
export interface StayRoom {
    id: string;
    ownerId: string;
    pricePerNight: bigint;
    isAvailable: boolean;
    checkInDate: string;
    amenities: Array<string>;
    checkOutDate: string;
    roomName: string;
    bookedDates: Array<string>;
}
export interface OwnerRevenue {
    ownerId: string;
    businessName: string;
    todayRevenue: bigint;
    totalRevenue: bigint;
}
export interface FoodItem {
    id: string;
    ownerId: string;
    isAvailable: boolean;
    description: string;
    itemName: string;
    isVeg: boolean;
    priceInr: bigint;
}
export type Result_7 = {
    __kind__: "ok";
    ok: RetailItem;
} | {
    __kind__: "err";
    err: string;
};
export interface Booking {
    id: string;
    status: BookingStatus;
    deliveryFee: bigint;
    ownerId: string;
    userId: string;
    createdAt: Timestamp;
    checkInDate: string;
    upiRef: string;
    slotDate: string;
    category: Category;
    checkOutDate: string;
    amountInr: bigint;
    itemRef: string;
}
export type Result_6 = {
    __kind__: "ok";
    ok: StayRoom;
} | {
    __kind__: "err";
    err: string;
};
export type Result_9 = {
    __kind__: "ok";
    ok: FoodItem;
} | {
    __kind__: "err";
    err: string;
};
export type UserId = string;
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type Result_3 = {
    __kind__: "ok";
    ok: Notification;
} | {
    __kind__: "err";
    err: string;
};
export type Result_10 = {
    __kind__: "ok";
    ok: CategoryEntry;
} | {
    __kind__: "err";
    err: string;
};
export interface Notification {
    id: string;
    title: string;
    body: string;
    createdAt: Timestamp;
    soundType: SoundType;
    isRead: boolean;
    target: string;
}
export type Result_8 = {
    __kind__: "ok";
    ok: PlaySlot;
} | {
    __kind__: "err";
    err: string;
};
export interface AdminStats {
    todayBookings: bigint;
    platformRevenue: bigint;
    totalUsers: bigint;
    totalOwners: bigint;
}
export interface RetailItem {
    id: string;
    inStock: boolean;
    ownerId: string;
    deliveryFeePerKm: bigint;
    itemName: string;
    quantity: bigint;
    category: string;
    priceInr: bigint;
}
export interface Ticket {
    id: string;
    status: TicketStatus;
    messages: Array<TicketMessage>;
    ownerId?: string;
    createdAt: Timestamp;
    description: string;
    imageUrl?: string;
    category: string;
    raisedBy: string;
}
export interface ActivityEntry {
    action: string;
    timestamp: Timestamp;
}
export interface TicketMessage {
    text: string;
    sender: string;
    timestamp: Timestamp;
}
export enum BookingStatus {
    pending = "pending",
    completed = "completed",
    accepted = "accepted",
    declined = "declined"
}
export enum Category {
    retail = "retail",
    food = "food",
    play = "play",
    stay = "stay"
}
export enum SoundType {
    alarm = "alarm",
    ping = "ping",
    silent = "silent"
}
export enum SubscriptionStatus {
    active = "active",
    expired = "expired",
    inactive = "inactive"
}
export enum TicketStatus {
    resolved = "resolved",
    open = "open"
}
export enum UserRole {
    admin = "admin",
    owner = "owner",
    user = "user"
}
export interface backendInterface {
    addBookedDate(roomId: string, date: string): Promise<Result>;
    addCategory(name: string, iconEmoji: string, tableType: Category, searchKeywords: Array<string>): Promise<Result_10>;
    addFoodItem(ownerId: string, itemName: string, priceInr: bigint, isVeg: boolean, description: string): Promise<Result_9>;
    addPlaySlot(ownerId: string, slotDate: string, startTime: string, endTime: string, surfaceType: string, hourlyRate: bigint, description: string): Promise<Result_8>;
    addRetailItem(ownerId: string, itemName: string, priceInr: bigint, category: string, quantity: bigint): Promise<Result_7>;
    addStayRoom(ownerId: string, roomName: string, amenities: Array<string>, pricePerNight: bigint): Promise<Result_6>;
    addTicketMessage(ticketId: string, sender: string, text: string): Promise<Result>;
    banUser(id: string, isBanned: boolean): Promise<Result>;
    completeOwnerOnboarding(userId: string, businessName: string, category: Category, upiId: string): Promise<Result_5>;
    createBooking(userId: string, ownerId: string, category: Category, itemRef: string, amountInr: bigint, upiRef: string, checkInDate: string, checkOutDate: string, slotDate: string, deliveryFee: bigint): Promise<Result_4>;
    createNotification(target: string, title: string, body: string, soundType: SoundType): Promise<Result_3>;
    createStayBooking(roomId: string, checkInDate: string, checkOutDate: string): Promise<Result>;
    createTicket(raisedBy: string, ownerId: string | null, category: string, description: string, imageUrl: string | null): Promise<Result_2>;
    deleteCategory(id: string): Promise<Result>;
    deleteFoodItem(id: string): Promise<Result>;
    deleteOwner(id: string): Promise<Result>;
    deleteUser(id: string): Promise<Result>;
    getActiveCategories(): Promise<Array<CategoryEntry>>;
    getActiveOwners(): Promise<Array<OwnerRecord>>;
    getAdminStats(): Promise<AdminStats>;
    getAllBookings(): Promise<Array<Booking>>;
    getAllCategories(): Promise<Array<CategoryEntry>>;
    getAllFoodItems(): Promise<Array<FoodItem>>;
    getAllNotifications(): Promise<Array<Notification>>;
    getAllOwners(): Promise<Array<OwnerRecord>>;
    getAllOwnersAdmin(): Promise<Array<OwnerRecord>>;
    getAllPlaySlots(): Promise<Array<PlaySlot>>;
    getAllRetailItems(): Promise<Array<RetailItem>>;
    getAllStayRooms(): Promise<Array<StayRoom>>;
    getAllTickets(): Promise<Array<Ticket>>;
    getAllUsers(): Promise<Array<UserRecord>>;
    getBookingsByOwner(ownerId: string): Promise<Array<Booking>>;
    getBookingsByUser(userId: string): Promise<Array<Booking>>;
    getDeliveryFee(ownerId: string, customerLat: number, customerLng: number): Promise<bigint>;
    getFoodItemsByOwner(ownerId: string): Promise<Array<FoodItem>>;
    getNotificationsByTarget(target: string): Promise<Array<Notification>>;
    getOwnerById(id: string): Promise<OwnerRecord | null>;
    getOwnersByCategory(category: Category): Promise<Array<OwnerRecord>>;
    getPlaySlotsByOwner(ownerId: string): Promise<Array<PlaySlot>>;
    getRetailItemsByOwner(ownerId: string): Promise<Array<RetailItem>>;
    getRevenueByOwner(): Promise<Array<OwnerRevenue>>;
    getSlotsByDate(ownerId: string, date: string): Promise<Array<PlaySlot>>;
    getStayAvailability(roomId: string, checkInDate: string, checkOutDate: string): Promise<boolean>;
    getStayRoomsByOwner(ownerId: string): Promise<Array<StayRoom>>;
    getTicketsByOwner(ownerId: string): Promise<Array<Ticket>>;
    getTicketsByUser(userId: string): Promise<Array<Ticket>>;
    getUserById(id: string): Promise<UserRecord | null>;
    logActivity(userId: string, action: string): Promise<void>;
    markNotificationRead(id: string): Promise<Result>;
    resolveTicket(id: string): Promise<Result>;
    signinUser(phone: string, password: string): Promise<Result_1>;
    signupUser(name: string, phone: string, password: string, role: UserRole, gpsLat: number, gpsLng: number, locationText: string): Promise<Result_1>;
    toggleSlotBooking(id: string, isBooked: boolean, bookedByUserId: string | null): Promise<Result>;
    updateBookingStatus(id: string, status: BookingStatus): Promise<Result>;
    updateCategory(id: string, name: string, iconEmoji: string, isActive: boolean, searchKeywords: Array<string>): Promise<Result>;
    updateDeliveryFeePerKm(ownerId: string, rate: bigint): Promise<Result>;
    updateFoodItem(id: string, itemName: string, priceInr: bigint, isVeg: boolean, description: string, isAvailable: boolean): Promise<Result>;
    updateOwnerProfile(id: string, businessName: string, upiId: string, isActive: boolean): Promise<Result>;
    updatePlaySlot(id: string, slotTime: string, surfaceType: string, hourlyRate: bigint, description: string): Promise<Result>;
    updateRetailItem(id: string, itemName: string, priceInr: bigint, category: string, inStock: boolean, quantity: bigint): Promise<Result>;
    updateStayRoom(id: string, roomName: string, amenities: Array<string>, pricePerNight: bigint, isAvailable: boolean): Promise<Result>;
    updateSubscriptionStatus(ownerId: string, subscriptionStatus: SubscriptionStatus, expiryDate: Timestamp, txId: string): Promise<Result>;
    updateUserProfile(id: string, name: string, locationText: string, gpsLat: number, gpsLng: number): Promise<Result>;
    verifyOwner(id: string): Promise<Result>;
    verifySubscriptionPayment(ownerId: string, txId: string): Promise<Result>;
}
import type { ActivityEntry as _ActivityEntry, Booking as _Booking, BookingStatus as _BookingStatus, Category as _Category, CategoryEntry as _CategoryEntry, FoodItem as _FoodItem, Notification as _Notification, OwnerRecord as _OwnerRecord, PlaySlot as _PlaySlot, Result as _Result, Result_1 as _Result_1, Result_10 as _Result_10, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result_6 as _Result_6, Result_7 as _Result_7, Result_8 as _Result_8, Result_9 as _Result_9, RetailItem as _RetailItem, SoundType as _SoundType, StayRoom as _StayRoom, SubscriptionStatus as _SubscriptionStatus, Ticket as _Ticket, TicketMessage as _TicketMessage, TicketStatus as _TicketStatus, Timestamp as _Timestamp, UserId as _UserId, UserRecord as _UserRecord, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBookedDate(arg0: string, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.addBookedDate(arg0, arg1);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBookedDate(arg0, arg1);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addCategory(arg0: string, arg1: string, arg2: Category, arg3: Array<string>): Promise<Result_10> {
        if (this.processError) {
            try {
                const result = await this.actor.addCategory(arg0, arg1, to_candid_Category_n3(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_Result_10_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCategory(arg0, arg1, to_candid_Category_n3(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_Result_10_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async addFoodItem(arg0: string, arg1: string, arg2: bigint, arg3: boolean, arg4: string): Promise<Result_9> {
        if (this.processError) {
            try {
                const result = await this.actor.addFoodItem(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Result_9_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFoodItem(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Result_9_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async addPlaySlot(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: string): Promise<Result_8> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlaySlot(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return from_candid_Result_8_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlaySlot(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return from_candid_Result_8_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async addRetailItem(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: bigint): Promise<Result_7> {
        if (this.processError) {
            try {
                const result = await this.actor.addRetailItem(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Result_7_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRetailItem(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Result_7_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async addStayRoom(arg0: string, arg1: string, arg2: Array<string>, arg3: bigint): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.addStayRoom(arg0, arg1, arg2, arg3);
                return from_candid_Result_6_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStayRoom(arg0, arg1, arg2, arg3);
            return from_candid_Result_6_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async addTicketMessage(arg0: string, arg1: string, arg2: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.addTicketMessage(arg0, arg1, arg2);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTicketMessage(arg0, arg1, arg2);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async banUser(arg0: string, arg1: boolean): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.banUser(arg0, arg1);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.banUser(arg0, arg1);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async completeOwnerOnboarding(arg0: string, arg1: string, arg2: Category, arg3: string): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.completeOwnerOnboarding(arg0, arg1, to_candid_Category_n3(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_Result_5_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeOwnerOnboarding(arg0, arg1, to_candid_Category_n3(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_Result_5_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBooking(arg0: string, arg1: string, arg2: Category, arg3: string, arg4: bigint, arg5: string, arg6: string, arg7: string, arg8: string, arg9: bigint): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0, arg1, to_candid_Category_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return from_candid_Result_4_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0, arg1, to_candid_Category_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return from_candid_Result_4_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async createNotification(arg0: string, arg1: string, arg2: string, arg3: SoundType): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotification(arg0, arg1, arg2, to_candid_SoundType_n36(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Result_3_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotification(arg0, arg1, arg2, to_candid_SoundType_n36(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Result_3_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async createStayBooking(arg0: string, arg1: string, arg2: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.createStayBooking(arg0, arg1, arg2);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStayBooking(arg0, arg1, arg2);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTicket(arg0: string, arg1: string | null, arg2: string, arg3: string, arg4: string | null): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.createTicket(arg0, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Result_2_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTicket(arg0, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Result_2_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCategory(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteFoodItem(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFoodItem(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFoodItem(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteOwner(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOwner(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOwner(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteUser(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveCategories(): Promise<Array<CategoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveCategories();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveCategories();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveOwners(): Promise<Array<OwnerRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveOwners();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveOwners();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminStats(): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return result;
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCategories(): Promise<Array<CategoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCategories();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCategories();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFoodItems(): Promise<Array<FoodItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFoodItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFoodItems();
            return result;
        }
    }
    async getAllNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotifications();
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotifications();
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOwners(): Promise<Array<OwnerRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOwners();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOwners();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllOwnersAdmin(): Promise<Array<OwnerRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOwnersAdmin();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOwnersAdmin();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPlaySlots(): Promise<Array<PlaySlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlaySlots();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlaySlots();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRetailItems(): Promise<Array<RetailItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRetailItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRetailItems();
            return result;
        }
    }
    async getAllStayRooms(): Promise<Array<StayRoom>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStayRooms();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStayRooms();
            return result;
        }
    }
    async getAllTickets(): Promise<Array<Ticket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTickets();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTickets();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<UserRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByOwner(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByOwner(arg0);
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByOwner(arg0);
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByUser(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByUser(arg0);
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByUser(arg0);
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDeliveryFee(arg0: string, arg1: number, arg2: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeliveryFee(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeliveryFee(arg0, arg1, arg2);
            return result;
        }
    }
    async getFoodItemsByOwner(arg0: string): Promise<Array<FoodItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFoodItemsByOwner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFoodItemsByOwner(arg0);
            return result;
        }
    }
    async getNotificationsByTarget(arg0: string): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotificationsByTarget(arg0);
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotificationsByTarget(arg0);
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnerById(arg0: string): Promise<OwnerRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnerById(arg0);
                return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnerById(arg0);
            return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOwnersByCategory(arg0: Category): Promise<Array<OwnerRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnersByCategory(to_candid_Category_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnersByCategory(to_candid_Category_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlaySlotsByOwner(arg0: string): Promise<Array<PlaySlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlaySlotsByOwner(arg0);
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlaySlotsByOwner(arg0);
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRetailItemsByOwner(arg0: string): Promise<Array<RetailItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRetailItemsByOwner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRetailItemsByOwner(arg0);
            return result;
        }
    }
    async getRevenueByOwner(): Promise<Array<OwnerRevenue>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevenueByOwner();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevenueByOwner();
            return result;
        }
    }
    async getSlotsByDate(arg0: string, arg1: string): Promise<Array<PlaySlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSlotsByDate(arg0, arg1);
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSlotsByDate(arg0, arg1);
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStayAvailability(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getStayAvailability(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStayAvailability(arg0, arg1, arg2);
            return result;
        }
    }
    async getStayRoomsByOwner(arg0: string): Promise<Array<StayRoom>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStayRoomsByOwner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStayRoomsByOwner(arg0);
            return result;
        }
    }
    async getTicketsByOwner(arg0: string): Promise<Array<Ticket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTicketsByOwner(arg0);
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTicketsByOwner(arg0);
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTicketsByUser(arg0: string): Promise<Array<Ticket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTicketsByUser(arg0);
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTicketsByUser(arg0);
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserById(arg0: string): Promise<UserRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserById(arg0);
                return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserById(arg0);
            return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async logActivity(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logActivity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logActivity(arg0, arg1);
            return result;
        }
    }
    async markNotificationRead(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async resolveTicket(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveTicket(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveTicket(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async signinUser(arg0: string, arg1: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.signinUser(arg0, arg1);
                return from_candid_Result_1_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.signinUser(arg0, arg1);
            return from_candid_Result_1_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async signupUser(arg0: string, arg1: string, arg2: string, arg3: UserRole, arg4: number, arg5: number, arg6: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.signupUser(arg0, arg1, arg2, to_candid_UserRole_n64(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
                return from_candid_Result_1_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.signupUser(arg0, arg1, arg2, to_candid_UserRole_n64(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6);
            return from_candid_Result_1_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleSlotBooking(arg0: string, arg1: boolean, arg2: string | null): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleSlotBooking(arg0, arg1, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleSlotBooking(arg0, arg1, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBookingStatus(arg0: string, arg1: BookingStatus): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n66(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n66(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCategory(arg0: string, arg1: string, arg2: string, arg3: boolean, arg4: Array<string>): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategory(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategory(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDeliveryFeePerKm(arg0: string, arg1: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeliveryFeePerKm(arg0, arg1);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeliveryFeePerKm(arg0, arg1);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateFoodItem(arg0: string, arg1: string, arg2: bigint, arg3: boolean, arg4: string, arg5: boolean): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFoodItem(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFoodItem(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOwnerProfile(arg0: string, arg1: string, arg2: string, arg3: boolean): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOwnerProfile(arg0, arg1, arg2, arg3);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOwnerProfile(arg0, arg1, arg2, arg3);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePlaySlot(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlaySlot(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlaySlot(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateRetailItem(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: boolean, arg5: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRetailItem(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRetailItem(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateStayRoom(arg0: string, arg1: string, arg2: Array<string>, arg3: bigint, arg4: boolean): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStayRoom(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStayRoom(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSubscriptionStatus(arg0: string, arg1: SubscriptionStatus, arg2: Timestamp, arg3: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubscriptionStatus(arg0, to_candid_SubscriptionStatus_n68(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubscriptionStatus(arg0, to_candid_SubscriptionStatus_n68(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserProfile(arg0: string, arg1: string, arg2: string, arg3: number, arg4: number): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyOwner(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyOwner(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyOwner(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifySubscriptionPayment(arg0: string, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.verifySubscriptionPayment(arg0, arg1);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifySubscriptionPayment(arg0, arg1);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BookingStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_CategoryEntry_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CategoryEntry): CategoryEntry {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_OwnerRecord_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OwnerRecord): OwnerRecord {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_PlaySlot_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlaySlot): PlaySlot {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Result_10_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_10): Result_10 {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Result_5_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_5): Result_5 {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Result_6_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_6): Result_6 {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Result_7_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_7): Result_7 {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Result_8_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_8): Result_8 {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Result_9_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_9): Result_9 {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_SoundType_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SoundType): SoundType {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionStatus): SubscriptionStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_TicketStatus_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TicketStatus): TicketStatus {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_Ticket_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Ticket): Ticket {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_UserRecord_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRecord): UserRecord {
    return from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OwnerRecord]): OwnerRecord | null {
    return value.length === 0 ? null : from_candid_OwnerRecord_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserRecord]): UserRecord | null {
    return value.length === 0 ? null : from_candid_UserRecord_n58(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    startTime: string;
    endTime: string;
    ownerId: string;
    surfaceType: string;
    bookedByUserId: [] | [string];
    hourlyRate: bigint;
    description: string;
    slotDate: string;
    slotTime: string;
    isBooked: boolean;
}): {
    id: string;
    startTime: string;
    endTime: string;
    ownerId: string;
    surfaceType: string;
    bookedByUserId?: string;
    hourlyRate: bigint;
    description: string;
    slotDate: string;
    slotTime: string;
    isBooked: boolean;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        endTime: value.endTime,
        ownerId: value.ownerId,
        surfaceType: value.surfaceType,
        bookedByUserId: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.bookedByUserId)),
        hourlyRate: value.hourlyRate,
        description: value.description,
        slotDate: value.slotDate,
        slotTime: value.slotTime,
        isBooked: value.isBooked
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    subscriptionExpiryDate: _Timestamp;
    lastSubscriptionTxId: string;
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
    businessName: string;
    isActive: boolean;
    lastSubscriptionPaymentDate: _Timestamp;
    activityLog: Array<_ActivityEntry>;
    subscriptionStatus: _SubscriptionStatus;
    isVerified: boolean;
    upiId: string;
    isBanned: boolean;
    category: _Category;
    passwordHash: string;
    phone: string;
    locationText: string;
    gpsLat: number;
    gpsLng: number;
}): {
    id: UserId;
    subscriptionExpiryDate: Timestamp;
    lastSubscriptionTxId: string;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    businessName: string;
    isActive: boolean;
    lastSubscriptionPaymentDate: Timestamp;
    activityLog: Array<ActivityEntry>;
    subscriptionStatus: SubscriptionStatus;
    isVerified: boolean;
    upiId: string;
    isBanned: boolean;
    category: Category;
    passwordHash: string;
    phone: string;
    locationText: string;
    gpsLat: number;
    gpsLng: number;
} {
    return {
        id: value.id,
        subscriptionExpiryDate: value.subscriptionExpiryDate,
        lastSubscriptionTxId: value.lastSubscriptionTxId,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n26(_uploadFile, _downloadFile, value.role),
        businessName: value.businessName,
        isActive: value.isActive,
        lastSubscriptionPaymentDate: value.lastSubscriptionPaymentDate,
        activityLog: value.activityLog,
        subscriptionStatus: from_candid_SubscriptionStatus_n28(_uploadFile, _downloadFile, value.subscriptionStatus),
        isVerified: value.isVerified,
        upiId: value.upiId,
        isBanned: value.isBanned,
        category: from_candid_Category_n9(_uploadFile, _downloadFile, value.category),
        passwordHash: value.passwordHash,
        phone: value.phone,
        locationText: value.locationText,
        gpsLat: value.gpsLat,
        gpsLng: value.gpsLng
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _BookingStatus;
    deliveryFee: bigint;
    ownerId: string;
    userId: string;
    createdAt: _Timestamp;
    checkInDate: string;
    upiRef: string;
    slotDate: string;
    category: _Category;
    checkOutDate: string;
    amountInr: bigint;
    itemRef: string;
}): {
    id: string;
    status: BookingStatus;
    deliveryFee: bigint;
    ownerId: string;
    userId: string;
    createdAt: Timestamp;
    checkInDate: string;
    upiRef: string;
    slotDate: string;
    category: Category;
    checkOutDate: string;
    amountInr: bigint;
    itemRef: string;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n34(_uploadFile, _downloadFile, value.status),
        deliveryFee: value.deliveryFee,
        ownerId: value.ownerId,
        userId: value.userId,
        createdAt: value.createdAt,
        checkInDate: value.checkInDate,
        upiRef: value.upiRef,
        slotDate: value.slotDate,
        category: from_candid_Category_n9(_uploadFile, _downloadFile, value.category),
        checkOutDate: value.checkOutDate,
        amountInr: value.amountInr,
        itemRef: value.itemRef
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    body: string;
    createdAt: _Timestamp;
    soundType: _SoundType;
    isRead: boolean;
    target: string;
}): {
    id: string;
    title: string;
    body: string;
    createdAt: Timestamp;
    soundType: SoundType;
    isRead: boolean;
    target: string;
} {
    return {
        id: value.id,
        title: value.title,
        body: value.body,
        createdAt: value.createdAt,
        soundType: from_candid_SoundType_n42(_uploadFile, _downloadFile, value.soundType),
        isRead: value.isRead,
        target: value.target
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _TicketStatus;
    messages: Array<_TicketMessage>;
    ownerId: [] | [string];
    createdAt: _Timestamp;
    description: string;
    imageUrl: [] | [string];
    category: string;
    raisedBy: string;
}): {
    id: string;
    status: TicketStatus;
    messages: Array<TicketMessage>;
    ownerId?: string;
    createdAt: Timestamp;
    description: string;
    imageUrl?: string;
    category: string;
    raisedBy: string;
} {
    return {
        id: value.id,
        status: from_candid_TicketStatus_n49(_uploadFile, _downloadFile, value.status),
        messages: value.messages,
        ownerId: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.ownerId)),
        createdAt: value.createdAt,
        description: value.description,
        imageUrl: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.imageUrl)),
        category: value.category,
        raisedBy: value.raisedBy
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
    activityLog: Array<_ActivityEntry>;
    isBanned: boolean;
    passwordHash: string;
    phone: string;
    locationText: string;
    gpsLat: number;
    gpsLng: number;
}): {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    activityLog: Array<ActivityEntry>;
    isBanned: boolean;
    passwordHash: string;
    phone: string;
    locationText: string;
    gpsLat: number;
    gpsLng: number;
} {
    return {
        id: value.id,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n26(_uploadFile, _downloadFile, value.role),
        activityLog: value.activityLog,
        isBanned: value.isBanned,
        passwordHash: value.passwordHash,
        phone: value.phone,
        locationText: value.locationText,
        gpsLat: value.gpsLat,
        gpsLng: value.gpsLng
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    isActive: boolean;
    iconEmoji: string;
    searchKeywords: Array<string>;
    tableType: _Category;
}): {
    id: string;
    name: string;
    isActive: boolean;
    iconEmoji: string;
    searchKeywords: Array<string>;
    tableType: Category;
} {
    return {
        id: value.id,
        name: value.name,
        isActive: value.isActive,
        iconEmoji: value.iconEmoji,
        searchKeywords: value.searchKeywords,
        tableType: from_candid_Category_n9(_uploadFile, _downloadFile, value.tableType)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    retail: null;
} | {
    food: null;
} | {
    play: null;
} | {
    stay: null;
}): Category {
    return "retail" in value ? Category.retail : "food" in value ? Category.food : "play" in value ? Category.play : "stay" in value ? Category.stay : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _FoodItem;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: FoodItem;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _PlaySlot;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: PlaySlot;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_PlaySlot_n15(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _RetailItem;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: RetailItem;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _StayRoom;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: StayRoom;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _OwnerRecord;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: OwnerRecord;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_OwnerRecord_n24(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    owner: null;
} | {
    user: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "owner" in value ? UserRole.owner : "user" in value ? UserRole.user : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    expired: null;
} | {
    inactive: null;
}): SubscriptionStatus {
    return "active" in value ? SubscriptionStatus.active : "expired" in value ? SubscriptionStatus.expired : "inactive" in value ? SubscriptionStatus.inactive : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Booking;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Booking;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Booking_n32(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    accepted: null;
} | {
    declined: null;
}): BookingStatus {
    return "pending" in value ? BookingStatus.pending : "completed" in value ? BookingStatus.completed : "accepted" in value ? BookingStatus.accepted : "declined" in value ? BookingStatus.declined : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Notification;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Notification;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Notification_n40(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    alarm: null;
} | {
    ping: null;
} | {
    silent: null;
}): SoundType {
    return "alarm" in value ? SoundType.alarm : "ping" in value ? SoundType.ping : "silent" in value ? SoundType.silent : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Ticket;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Ticket;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Ticket_n47(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    open: null;
}): TicketStatus {
    return "resolved" in value ? TicketStatus.resolved : "open" in value ? TicketStatus.open : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CategoryEntry;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: CategoryEntry;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_CategoryEntry_n7(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserRecord;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserRecord;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserRecord_n58(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CategoryEntry>): Array<CategoryEntry> {
    return value.map((x)=>from_candid_CategoryEntry_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OwnerRecord>): Array<OwnerRecord> {
    return value.map((x)=>from_candid_OwnerRecord_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlaySlot>): Array<PlaySlot> {
    return value.map((x)=>from_candid_PlaySlot_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Ticket>): Array<Ticket> {
    return value.map((x)=>from_candid_Ticket_n47(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserRecord>): Array<UserRecord> {
    return value.map((x)=>from_candid_UserRecord_n58(_uploadFile, _downloadFile, x));
}
function to_candid_BookingStatus_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n67(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_SoundType_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SoundType): _SoundType {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionStatus_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): _SubscriptionStatus {
    return to_candid_variant_n69(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n65(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SoundType): {
    alarm: null;
} | {
    ping: null;
} | {
    silent: null;
} {
    return value == SoundType.alarm ? {
        alarm: null
    } : value == SoundType.ping ? {
        ping: null
    } : value == SoundType.silent ? {
        silent: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    retail: null;
} | {
    food: null;
} | {
    play: null;
} | {
    stay: null;
} {
    return value == Category.retail ? {
        retail: null
    } : value == Category.food ? {
        food: null
    } : value == Category.play ? {
        play: null
    } : value == Category.stay ? {
        stay: null
    } : value;
}
function to_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    owner: null;
} | {
    user: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.owner ? {
        owner: null
    } : value == UserRole.user ? {
        user: null
    } : value;
}
function to_candid_variant_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    pending: null;
} | {
    completed: null;
} | {
    accepted: null;
} | {
    declined: null;
} {
    return value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.completed ? {
        completed: null
    } : value == BookingStatus.accepted ? {
        accepted: null
    } : value == BookingStatus.declined ? {
        declined: null
    } : value;
}
function to_candid_variant_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): {
    active: null;
} | {
    expired: null;
} | {
    inactive: null;
} {
    return value == SubscriptionStatus.active ? {
        active: null
    } : value == SubscriptionStatus.expired ? {
        expired: null
    } : value == SubscriptionStatus.inactive ? {
        inactive: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
